Return empty string when value is None
Now _humanize doesn't check whether value is None. As a result,
the following error occurs.

return value.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

Fix the problem by returning empty string.